services:
  navio-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: navio-frontend
    ports:
      - "5174:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
